services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mask-bot-bloc:
    image: ghcr.io/seanmc9/mask-bloc-bot:prod 
    env_file: .env.vars
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      mode: global
    restart: always
