services:
  dev-mask-bot-bloc:
    container_name: dev-mask-bloc-bot
    image: ghcr.io/seanmc9/mask-bloc-bot:dev
    env_file: .env.dev
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      mode: global
    restart: always

  prod-mask-bot-bloc:
    container_name: prod-mask-bloc-bot
    image: ghcr.io/seanmc9/mask-bloc-bot:prod
    env_file: .env.prod
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      mode: global
    restart: always

  watchtower:
    container_name: mask-bloc-bot-watchtower
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
      - "--cleanup"
      - "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
